//  Created by Nicholas Goncharov.
//
//  Code realizate encoding and decoding RC4 algorithm 

#include "RC4.h"

FILE *in_file, *out_file;

int main() {
    char key[100];
    char input_file_name[100];
    char output_file_name[100];
    
    printf("input file: ");
    scanf("%s", input_file_name);                   // Read input and output files and open
    printf("\noutput file: ");                      // their for binary read and write
    scanf("%s", output_file_name);
    
    printf("\nWrite a key: ");                      // Read a key (string, max size: 100)
    scanf("%s", key);
    
    rc4_init(key);                                  // Generated bytes chain use a key
     
    in_file = fopen(input_file_name, "rb");
    out_file = fopen(output_file_name, "wb");
    
    unsigned int s = fgetc(in_file);                // We take 1 byte from input file and xor
    while(!feof(in_file))  {                        // (sum mod 2) it with 1 pseudo-random
        fputc(s ^ rc4_give_byte(), out_file);       // byte, what we generated. This give us
        s = fgetc(in_file);                         // chance to use this operation for
    }                                               // encoding and decoding
    return 0;
}
